model = dict(
    type='Recognizer3D',
    backbone=dict(
        type='ConvNeXt3d',
        arch='tiny',
        pretrained=None,
        pretrained2d=True,
        stem_patch_size=(2, 4, 4),
        inflate=(1, 1, 1, 1),
        inflate_kernel_size=(8, 7, 7),
        inflate_init_type='center',
        drop_path_rate=0.1),
    data_preprocessor=dict(
        type='ActionDataPreprocessor',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        format_shape='NCTHW'),
    cls_head=dict(
        type='I3DHead',
        in_channels=768,
        num_classes=400,
        spatial_type='avg',
        dropout_ratio=0.5,
        average_clips='prob'))
